export default {
  icon: require('./icon.png'),
  tick: require('./tick.png'),
  excellentSignal: require('./excellent-signal.png'),
  lockedImage: require('./logo-locked.png'),
  unlockedImage: require('./logo-unlocked.png'),
  goodSignal: require('./good-signal.png'),
  averageSignal: require('./average-signal.png'),
  weakSignal: require('./weak-signal.png'),
  rpm: require('./rpm.png'),
  settings: require('./settings.png'),
  info: require('./info.png'),
  power: require('./power.png'),
  logo: require('./logo.png'),
  qr: require('./qr.png'),
  zoom_in: require('./zoom_in.png'),
  zoom_out: require('./zoom_out.png'),
  unavailable: require('./unavailable.png'),
  warning: require('./warning.png'),
  core: require('./core.png'),
  machine: require('./machine.png'),
  sensing: require('./sensing.png'),
  switchCamera: require('./SwitchCamera_icon.png'),
  infoImage: require('./connect-info.png'),
  clock: require('./clock.png'),
  notificationsWhite: require('./notifications_white.png')
};
