require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'rn_template' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'react-native-google-analytics-bridge', :path => '../node_modules/react-native-google-analytics-bridge'

  pod 'RNPinchZoomImage', :path => '../node_modules/react-native-pinch-zoom-image'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'


  target 'rn_templateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'rn_template-tvOS' do
  # Pods for rn_template-tvOS

  target 'rn_template-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
