export const Actions = {
  SET_TOKEN: 'SET_AUTH_TOKEN',
  SET_IS_LOGGED_IN: 'SET_IS_LOGGED_IN',

  NOTIFY: 'SHOW_SNACKBAR',
  NOTIFY_CLOSE: 'CLOSE_SHOW_SNACKBAR',

  SHOW_PROGRESS_BAR: 'SHOW_PROGRESS_BAR',
  HIDE_PROGRESS_BAR: 'HIDE_PROGRESS_BAR',

  SHOW_DEFECT_STOP: 'SHOW_DEFECT_STOP',
  HIDE_DEFECT_STOP: 'HIDE_DEFECT_STOP',

  SHOW_SESSION_TIMOUT: 'SHOW_SESSION_TIMEOUT',
  HIDE_SESSION_TIMEOUT: 'HIDE_SESSION_TIMEOUT',

  SHOW_DISCONNECTED_ERROR: 'SHOW_DISCONNECTED_ERROR',
  HIDE_DISCONNECTED_ERROR: 'HIDE_DISCONNECTED_ERROR',

  SET_ROLL_NUMBER: 'SET_ROLL_NUMBER',
  SET_MACHINE_AND_ROLL_NUMBER: 'SET_MACHINE_AND_ROLL_NUMBER',
  SET_DEFECT_ALERT: 'SET_DEFECT_ALERT',
  SET_SELECTED_FABRIC: 'SET_SELECTED_FABRIC',
  SET_PRODUCING_NUMBER: 'SET_PRODUCING_NUMBER',

  SET_DEVICE_INFO: 'SET_DEVICE_INFO',
  SET_STOPPAGE_STATE: 'SET_STOPPAGE_STATE',
  SET_SETTINGS: 'SET_SETTINGS',
  UPDATE_RPM: 'UPDATE_RPM',
  UPDATE_LIVE_FEED: 'UPDATE_LIVE_FEED',
  EMPTY_LIVE_FEED: 'EMPTY_LIVE_FEED',
  UPDATE_DEFECT_COUNT_AND_TIMESTAMP: 'UPDATE_DEFECT_COUNT_AND_TIMESTAMP',
  UPDATE_DEFECTED_FRAMES: 'UPDATE_DEFECTED_FRAMES',

  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_UPDATING: 'SET_UPDATING',
  SET_CUT_ROLL_UPDATING: 'SET_CUT_ROLL_UPDATING',

  SET_CUT_ROLL_PO_FALLBACK: 'SET_CUT_ROLL_PO_FALLBACK',
  SET_LOGIN_CREDENTIALS: 'SET_LOGIN_CREDENTIALS',
  SET_SETTINGS_TIME_STAMP: 'SET_SETTINGS_TIME_STAMP',

  UPDATE_SETTINGS_UNLOCK_PASSWORD: 'UPDATE_SETTINGS_UNLOCK_PASSWORD',

  SHOW_PING_ERROR_DIALOG: 'SHOW_PING_ERROR_DIALOG',
  HIDE_PING_ERROR_DIALOG: 'HIDE_PING_ERROR_DIALOG',

  SHOW_HIDE_SERVICES_DILOAG: 'SHOW_HIDE_SERVICES_DILOAG',
  ALL_FABRICS: 'ALL_FABRICS',
  LAST_IMAGE_TIME: 'LAST_IMAGE_TIME',
  CONNECTION_LOST: 'CONNECTION_LOST',
  IS_FROM_SETTING: 'IS_FROM_SETTING',
  SELECTED_AI_MODEL: 'SELECTED_AI_MODEL',

  DISABLE_HOME_ACTION: 'DISABLE_HOME_ACTION',
  FABRIC_DETAIL_DIALOG: 'FABRIC_DETAIL_DIALOG',
};
